apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices-app
spec:
  selector:
    app: auth
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
