apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: microservices-app
spec:
  selector:
    app: user-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
